### ISSUE TITLE
Ok, this is a request

### ISSUE THREAD

**Issue by BrendaPuckle** [Willard21/MineKhan#49] opened 2021-06-18 18:15 UTC
Hi, me again (probably super annoying) but....... can you add more plants maybe??????? It probably takes a while so I'll be patient.

**Comment by Willard21** [comment] 2021-06-18 19:30
Duplicate of #31

**Closed by Willard21** 2021-06-18 19:30 UTC

**Comment by BrendaPuckle** [comment] 2021-06-18 19:36
> Duplicate of #31

I haven't seen issue #31
