### ISSUE TITLE
When Should We Start Implementing Survival

### ISSUE THREAD

**Issue by SnehasishCodez** [Willard21/MineKhan#42] opened 2021-06-08 21:34 UTC
when would be a good time to start creating survival because as @Willard21 said currently if we implement it, it would be half-implemented when will MineKhan Be ready for survival beta?

**Comment by GuineaPigBridge** [comment] 2021-06-09 17:06
As in.... we could use the modded ver, and make it so it runs better, since the modded ver only runs at like 2 fps on my garbage school computer.... We need to make it more compact.

**Comment by Willard21** [comment] 2021-06-16 18:26
Duplicate of #25

**Closed by Willard21** 2021-06-16 18:26 UTC
