### ISSUE TITLE
Marketplace In MineKhan

### ISSUE THREAD

**Issue by SnehasishCodez** [Willard21/MineKhan#45] opened 2021-06-14 23:11 UTC
any ideas on when and how we should implement a marketplace in minekhan where you can access hundreds of player made worlds and mods

**Comment by SnehasishCodez** [comment] 2021-06-14 23:12
https://minekhan.thingmaker.repl.co/
this link above has a marketplace as well as many other features

**Comment by magic4792** [comment] 2021-06-17 22:09
> https://minekhan.thingmaker.repl.co/

the only problem is that players need to go to a seperate website, post save code (which takes forever to scroll through), and wait for their world to be posted.  It would be handy if:

1. the game had an option to upload save code directly to the marketplace (although the marketplace may get easily overloaded in mere weeks or possibly days)
2. the longer comments (especially with savecode, if possible) could collapse
3. another possible soltution which combines these two would be to make admin accounts, and allow normal users to submit worlds, through the marketplace, to admin for approval.  Again, could be easily overloaded, and would require extra work for admin accounts upon thingMake, but may also work extremely well.
I know thingMake made this version, but might as well comment :/

**Comment by harsha7addanki** [comment] 2021-06-24 01:46
I Agree, but the added blocks are cool!

**Comment by Willard21** [comment] 2021-07-14 20:22
Duplicate of #24

**Closed by Willard21** 2021-07-14 20:22 UTC
Labels: duplicate
